name = "PereiraMartinez2025"
uuid = "a5a4965e-6774-4fb4-b0b8-7072333bc421"
authors = ["Leandro Martinez <lmartine@unicamp.br> and contributors"]
version = "1.0.0"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
